
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package compiladorfinal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POTENCIA = 8;
  public static final int SUMA = 2;
  public static final int MULTIPLICACION = 6;
  public static final int EOF = 0;
  public static final int NUMERO = 3;
  public static final int ID = 10;
  public static final int error = 1;
  public static final int PUNTOCOMA = 4;
  public static final int DIVISION = 7;
  public static final int RAIZCUADRADA = 9;
  public static final int RESTA = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "NUMERO",
  "PUNTOCOMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIA",
  "RAIZCUADRADA",
  "ID"
  };
}

